sudo: false
langauge: node_js
cache: node_modules
before_script:
  - npm install -g gitbook-cli
script: npm install && gitbook install && gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _book/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
